apiVersion: v2
name: guidetofilecoin-xyz
description: Install guidetofilecoin.xyz to provide guidetofilecoin official web page.
version: 1.0.0
kubeVersion: < 1.28.0-0
home: https://guidetofilecoin.xyz/
keywords:
  - guidetofilecoin-xyz
sources:
  - https://github.com/guidetofilecoin/website
maintainers:
  - name: guidetofilecoin team
