apiVersion: apps/v1
kind: Deployment
metadata:
  name: guidetofilecoin-xyz-deployment
  labels:
    apptype: guidetofilecoin-xyz
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: guidetofilecoin-xyz
  template:
    metadata:
      labels:
        app: guidetofilecoin-xyz
        apptype: guidetofilecoin-xyz
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: guidetofilecoin-xyz
          image: gitdatateam/guidetofilecoin-xyz:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
