apiVersion: v1
kind: Service
metadata:
  name: guidetofilecoin-xyz-service
  labels:
    apptype: guidetofilecoin-xyz
spec:
  type: ClusterIP
  selector:
    app: guidetofilecoin-xyz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80